AWSTemplateFormatVersion: 2010-09-09
Resources:
  LOCATIONSERVICE:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: location-service
  DEMANDSERVICE:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: demand-service
  BEACONSERVICE:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: beacon-service
  PDASERVICE:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: pda-service